### PR TITLE
Added support for arrays in tables (headers/arguments)

### LINKED ISSUE #156: Cannot use sender-selected distribution
Currently it is not possible to use [sender-selected distribution](https://www.rabbitmq.com/sender-selected.html) due to lacking support to array fields in `Basic.publish`'s `:headers` (and, due to also using `to_type_tuple`, `Queue.bind`'s and `Queue.declare`'s `:arguments` also lack support for array fields).

I would expect this to work:
```
AMQP.Basic.publish(chan, "", "test1", "payload", headers: [CC: ["test2", "test3"]])
```

I have made a pull request to fix this where `to_type_tuple` is changed to `cast_table`, where all types in the table are cast and labeled as expected by `rabbitmq_common`. This includes any field values inside an array which was declared in `{:array, value}` form, which I am not sure if is desired. That is, an array's internal values are still cast even if the array is already in the cast form. This situation is exemplified in the last test.

The names `table`, `table_field` and `field_value` are taken from [rabbit-common](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_binary_generator.erl#L119-L143)

This is my first pull request on an Elixir project. Any feedback is appreciated!

### PR DESCRIPTION
**Pull request by leodag**
Fixes #156

### CODE REVIEW

**Comment by ono** [comment]
Totally makes sense! Congratulations to your first PR 👏:tada: It's a great work but I have a few requests...:

- Can you keep the function name `to_type_tuple` for now? That'd give me a clear idea about the implications. Also that ensures the backward compatibility.
- Likewise keep all `to_type_tuple` implementation as public to keep it backward compatible. If you can keep the changes minimum here, that will be great.
- Sorry, I just merged formatting change. Please rebase against master :pray:

I understand why you want to use `cast_table_field` but I guess you can still distinguish array with `Keyword.keyword?/1`?

Thanks!

**Comment by leodag** [comment]
Sorry for the (very!) late response. I should be able to answer in a few days for any more reviewing.

The big problem here is that I have to differentiate table fields and field values: table fields are `{"name", :type, value}`, while field values are unnamed: `{:type, value}`. Since  `to_type_tuple` does type inference to convert `{name, value}` into table fields, I did the same to convert `value` into field values. So the reason I can't make it all into a single functions is because a tuple with two elements would be ambiguous.

I didn't manage to find a naming convention for field values in line with `to_type_tuple`, that's why I wanted to rename them. But yes, it should be backwards compatible.

I turned `cast_table` and `cast_table_field` as clauses of `to_type_tuple` (so it acts the same as currently), and inlined `cast_internal_fields`, since it's really small and only used twice. I still need a new function `cast_field_value` to differentiate tuples with two elements though. If you have any better names, that'd be nice.

I left `cast_field_values` as private since it's only for values inside arrays, but I could make it public too if you prefer it like that.

**Comment by ono** [comment]
@leodag no problem. i couldn't respond quickly either. I ran out time today but I will take a look again next week.

**Comment by ono** [comment]
Great work. Thank you!!

**Pull request merged**
