### PR TITLE
Link Connection process to underlying AMQP connection

### PR DESCRIPTION
**Pull request by craigp**
Linking the processes would prevent leaving zombie AMQP connections lying around if the Connection process dies.

### CODE REVIEW

**Comment by craigp** [comment]
Rebased to main

**Comment by ono** [comment]
nice one! linking the process totally makes sense.

can you do me a favour? can you also make the equivalent change to `AMQP.Application.Channel` and its test?

**Comment by craigp** [comment]
> nice one! linking the process totally makes sense.
> 
> can you do me a favour? can you also make the equivalent change to `AMQP.Application.Channel` and its test?

I thought about doing that originally, but I wasn't sure that you'd want to take the AMQP connection down when a channel process died, since other channels might also be using it.

**Comment by ono** [comment]
let's merge this change then i will see if it makes sense to do the same for channel too.

**Pull request merged**
