### PR TITLE
mix: clean dependencies for great good

### PR DESCRIPTION
**Pull request by dch**
It seems we can simplify mix dependencies dramatically now - I believe the lager and mochiweb issues of last year are all gone. Incidentally this also resolves a pathological `mix deps.update --all` on our app which consumes over 50GiB of RAM while doing the dependency resolution, so ... that's a bonus.

I'm not really able to do significant testing of all the related Elixir & OTP versions, but "works for me" on OTP 22.1.5, RabbitMQ 3.8.1, and Elixir 1.9.3

### CODE REVIEW

**Comment by dch** [comment]
^ fails only with Elixir 1.6, which AFAICT isn't supported. I think it's reasonable to forge on & commit this.

**Comment by whatyouhide** [comment]
👏

**Comment by ono** [comment]
I'd like to support `3.7.x` on 1.x if possible. Let me think bit more about the best way supporting `3.8.x`.

**Comment by ono** [comment]
Sorry for being late. I am going to merge this and release this as `1.4.0-rc.0`.

- We remove some compatibilities with lower version of amqp_client and Elixir
- It has some impact so patch level version bump is not sufficient
- I believe we can do it with a minor version bump as it doesn't contain any API changes
- I will also update travis config and [wiki page](https://github.com/pma/amqp/wiki/Versions-and-Compatibilities)

Thanks!

**Pull request merged**
