### PR TITLE
adding return and confirmation handlers

### PR DESCRIPTION
**Pull request by marcelog**
Hello,

I couldn't find these features in the code, so maybe I'm missing something (or maybe not). This pull adds the capability of registering a confirmation handler and a return handler, when one wants to follow up on what happened with the sent messages on a more customized way. I hope you're ok with the location for the functions.

Thanks in advance!

### CODE REVIEW

**Comment by pma** [comment]
@marcelog Thanks for your contribution. 
I never added these before simply because so far Confirm.wait_for_confirms_or_die has been sufficient for my use case.

I'd just suggest moving `(un)register_return_handler` to the `Basic` module, since they're related to Basic.publish (with mandatory or immediate flags). I'm also not sure what is the term sent to the handler process. I'm guessing it's an Erlang record. Maybe it makes sense to map this to something else, as done in Basic.consume. What do you think?

**Comment by marcelog** [comment]
Thanks for the comments. I've moved the `(un)register_return_handler` functions to the Basic module.

Correct, they are erlang records. Would you rather have an "adapter process" for those and send a different message to the handler, like `{:basic_ack, ...}` and `{:basic_return, ...}` ?

I think it makes sense for consistency sake (if the amqp-lib details are hidden in one place, they should be hidden everywhere), although I'm not sure I like the overhead in code complexity in the library. Let me see how it could look like, and get back to you.

Cheers!

**Comment by marcelog** [comment]
The code looks something like this for the return handler with an adapter process. When calling the `register_return_handler`, a new process is spawned and it will receive the messages and send something similar to what a consume action sends, `{:basic_return, payload, amqp_msg}`:

```elixir
  @doc """
  Registers a process as a return handler for the given channel.
  """
  def register_return_handler(chan = %Channel{pid: pid}, handler_pid) do
    adapter_pid = spawn fn ->
      Process.flag(:trap_exit, true)
      Process.monitor(handler_pid)
      Process.monitor(chan.pid)
      do_return_handler(chan, handler_pid)
    end
    :amqp_channel.register_return_handler(pid, adapter_pid)
  end

  defp do_return_handler(chan, handler_pid) do
    receive do
      {basic_return(
        reply_code: reply_code,
        reply_text: reply_text,
        exchange: exchange,
        routing_key: routing_key
      ), amqp_msg(props: p_basic(content_type: content_type,
                               content_encoding: content_encoding,
                               headers: headers,
                               delivery_mode: delivery_mode,
                               priority: priority,
                               correlation_id: correlation_id,
                               reply_to: reply_to,
                               expiration: expiration,
                               message_id: message_id,
                               timestamp: timestamp,
                               type: type,
                               user_id: user_id,
                               app_id: app_id,
                               cluster_id: cluster_id
      ), payload: payload)} ->
        send handler_pid, {:basic_return, payload, %{
                                          reply_code: reply_code,
                                          reply_text: reply_text,
                                          exchange: exchange,
                                          routing_key: routing_key,
                                          content_type: content_type,
                                          content_encoding: content_encoding,
                                          headers: headers,
                                          delivery_mode: delivery_mode,
                                          priority: priority,
                                          correlation_id: correlation_id,
                                          reply_to: reply_to,
                                          expiration: expiration,
                                          message_id: message_id,
                                          timestamp: timestamp,
                                          type: type,
                                          user_id: user_id,
                                          app_id: app_id,
                                          cluster_id: cluster_id

        }}
        do_return_handler(chan, handler_pid)
      {:DOWN, _ref, :process, ^handler_pid, reason} ->
        unregister_return_handler(chan)
        exit(reason)
      {:DOWN, _ref, :process, _pid, reason} ->
        unregister_return_handler(chan)
        exit(reason)
    end
  end
```

Question: When calling `unregister_return_handler` this new adapter process should die. When consuming, there's the cancel message, but we don't have something like that in this case. How would you like to handle this scenario?

**Comment by pma** [comment]
@marcelog I agree with the remark about the overhead and extra complexity of the adapter process (both in Basic.consume and Basic.register_return_handler. On the other hand I really want to avoid exposing the erlang records and the macros required to manipulate them.

A compromise approach would be to implement AMQP.Consumer and AMQP.ReturnHandler. These modules would define the generic behaviour (i.e. the handle_info receiving erlang records) and this behaviour would be included in a custom module with `use AMQP.Consumer`. The implementation of the generic modules would be something like:

```elixir
      def handle_info(basic_consume_ok(consumer_tag: consumer_tag), state) do
        handle_info({:basic_consume_ok, %{consumer_tag: consumer_tag}}, state)
      end
```

In this case the overhead would be an extra function call instead of the extra message passing via adapter pid.

I'll try this approach with AMQP.Consumer first and see if it works.

**Comment by marcelog** [comment]
That sounds good :) Although if one wants to use a "receive" for a specific message (instead of handling it with a handle_info), the erlang record will be exposed anyway (just pointing this out to state a difference between the two approaches)

**Comment by pma** [comment]
@marcelog Pushed the proposed changes to the branch `pma_consumer_behaviour` (https://github.com/pma/amqp/commit/a4417abf1776ffb1b3008c372337e01e977b5ce2). 

It's true that someone may implement the handler process to handle the messages directly with handle_info. But one might as well just use the Erlang client directly in that case. 

This approach makes the code less complex, and replacing the adapter pid by a function call should result in less overhead (I haven't run any benchmarks).

Thoughts?

**Comment by marcelog** [comment]
Looks good. How about I open a new pull request but for this branch instead of master, and we can see how it looks like altogether before merging everything (new consumer and return/confirm handlers)?

**Comment by pma** [comment]
@marcelog Sorry for the long turnaround. I've looked at his again and the adapter process solution still looks easier to use. It only adds a few microseconds of overhead for the extra message passing, which shouldn't be a problem.

**Comment by pma** [comment]
Closing this for now. Will reopen if needed.

**Pull request closed without merging**
